#!/usr/bin/env python3
#
# SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
#
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


PROJECT_DIR = Path(__file__).resolve().parents[1]
BOARDS_DIR = PROJECT_DIR / "boards"
GEN_BMGR_DIR = PROJECT_DIR / "components" / "gen_bmgr_codes"

SUPPORTED_BOARDS = (
    "esp32_S3_DevKitC_1_breadboard",
    "esp32_S3_DevKitC_1_breadboard_smallscreen",
)

BOARD_SUPPORT_LINES = [
    'CONFIG_ESP_BOARD_PERIPH_I2C_SUPPORT=y',
    'CONFIG_ESP_BOARD_PERIPH_I2S_SUPPORT=y',
    'CONFIG_ESP_BOARD_PERIPH_LEDC_SUPPORT=y',
    'CONFIG_ESP_BOARD_PERIPH_RMT_SUPPORT=y',
    'CONFIG_ESP_BOARD_PERIPH_SPI_SUPPORT=y',
    'CONFIG_ESP_BOARD_DEV_AUDIO_CODEC_SUPPORT=y',
    'CONFIG_ESP_BOARD_DEV_CAMERA_SUPPORT=y',
    'CONFIG_ESP_BOARD_DEV_CUSTOM_SUPPORT=y',
    'CONFIG_ESP_BOARD_DEV_DISPLAY_LCD_SUPPORT=y',
    'CONFIG_ESP_BOARD_DEV_CAMERA_SUB_DVP_SUPPORT=y',
    'CONFIG_ESP_BOARD_DEV_DISPLAY_LCD_SUB_SPI_SUPPORT=y',
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Switch the active board-manager board for basic_demo.",
    )
    parser.add_argument("board", nargs="?", help="Target board name")
    parser.add_argument("--list", action="store_true", help="List supported boards")
    return parser.parse_args()


def fail(message: str) -> None:
    raise RuntimeError(message)


def board_symbol(board_name: str) -> str:
    normalized = re.sub(r"[^A-Za-z0-9]+", "_", board_name).upper()
    return f"CONFIG_ESP_BOARD_{normalized}"


def read_board_target(board_dir: Path) -> str:
    board_info = board_dir / "board_info.yaml"
    for line in board_info.read_text().splitlines():
        if line.startswith("chip:"):
            return line.split(":", 1)[1].strip()
    fail(f"chip not found in {board_info}")


def read_board_defaults(board_dir: Path) -> list[str]:
    defaults_path = board_dir / "sdkconfig.defaults.board"
    if not defaults_path.exists():
        return []

    lines: list[str] = []
    for raw_line in defaults_path.read_text().splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        lines.append(line)
    return lines


def write_if_changed(path: Path, content: str) -> bool:
    if path.exists() and path.read_text() == content:
        return False
    path.write_text(content)
    return True


def generate_cmakelists(board_name: str, board_dir: Path) -> str:
    return (
        "# Board information output\n"
        f'message(STATUS "Selected Board: {board_name}")\n'
        f'message(STATUS "Board Path: {board_dir}")\n'
        "\n"
        "idf_component_register(\n"
        f'    SRC_DIRS "." "../../boards/{board_name}"\n'
        f'    INCLUDE_DIRS "." "../../boards/{board_name}"\n'
        "    REQUIRES esp_board_manager\n"
        ")\n"
        "\n"
        "# This is equivalent to adding WHOLE_ARCHIVE option to the idf_component_register call above:\n"
        "idf_component_set_property(${COMPONENT_NAME} WHOLE_ARCHIVE TRUE)\n"
    )


def generate_kconfig(board_name: str) -> str:
    return (
        "# Auto-generated by esp_board_manager\n"
        "# DO NOT MODIFY THIS FILE MANUALLY\n"
        "\n"
        f"config {board_symbol(board_name)[len('CONFIG_'):]}\n"
        "    bool\n"
        "    default y\n"
        "\n"
        "config ESP_BOARD_NAME\n"
        "    string\n"
        f'    default "{board_name}"\n'
    )


def generate_board_manager_defaults(board_name: str, board_dir: Path) -> str:
    target = read_board_target(board_dir)
    defaults = read_board_defaults(board_dir)
    lines = [
        "# --- Board-specific configuration (managed by esp_board_manager) ---",
        f"# Board: {board_name}",
        f'CONFIG_IDF_TARGET="{target}"',
        f"{board_symbol(board_name)}=y",
        f'CONFIG_ESP_BOARD_NAME="{board_name}"',
        "",
        *BOARD_SUPPORT_LINES,
        "",
        *defaults,
        "# --- End of board-specific configuration ---",
        "",
    ]
    return "\n".join(lines)


def update_sdkconfig_file(path: Path, board_name: str, board_dir: Path) -> bool:
    if not path.exists():
        return False

    managed_keys = {
        "CONFIG_ESP_BOARD_NAME",
        "CONFIG_BASIC_DEMO_ENABLE_EMOTE",
        *[line.split("=", 1)[0] for line in BOARD_SUPPORT_LINES],
        *[line.split("=", 1)[0] for line in read_board_defaults(board_dir)],
    }

    raw_lines = path.read_text().splitlines()
    kept_lines: list[str] = []
    for line in raw_lines:
        if re.match(r"CONFIG_ESP_BOARD_[A-Z0-9_]+=y$", line):
            continue
        if line.startswith("# ") and line.endswith(" is not set"):
            disabled_key = line[2:].split(" ", 1)[0]
            if disabled_key in managed_keys:
                continue
        key = line.split("=", 1)[0]
        if key in managed_keys:
            continue
        kept_lines.append(line)

    update_lines = [
        f"{board_symbol(board_name)}=y",
        f'CONFIG_ESP_BOARD_NAME="{board_name}"',
        *BOARD_SUPPORT_LINES,
    ]
    update_lines.extend(read_board_defaults(board_dir))

    merged = "\n".join(kept_lines).rstrip()
    if merged:
        merged += "\n"
    merged += "\n".join(update_lines) + "\n"
    return write_if_changed(path, merged)


def main() -> int:
    args = parse_args()
    if args.list:
        for name in SUPPORTED_BOARDS:
            print(name)
        return 0

    if not args.board:
        fail("missing board name; pass --list to view supported boards")

    if args.board not in SUPPORTED_BOARDS:
        fail(f"unsupported board: {args.board}")

    board_dir = BOARDS_DIR / args.board
    if not board_dir.is_dir():
        fail(f"board directory does not exist: {board_dir}")

    changed: list[Path] = []

    cmakelists_path = GEN_BMGR_DIR / "CMakeLists.txt"
    if write_if_changed(cmakelists_path, generate_cmakelists(args.board, board_dir)):
        changed.append(cmakelists_path)

    kconfig_path = GEN_BMGR_DIR / "Kconfig.projbuild"
    if write_if_changed(kconfig_path, generate_kconfig(args.board)):
        changed.append(kconfig_path)

    defaults_path = GEN_BMGR_DIR / "board_manager.defaults"
    if write_if_changed(defaults_path, generate_board_manager_defaults(args.board, board_dir)):
        changed.append(defaults_path)

    for sdkconfig_name in ("sdkconfig", "sdkconfig.old"):
        sdkconfig_path = PROJECT_DIR / sdkconfig_name
        if update_sdkconfig_file(sdkconfig_path, args.board, board_dir):
            changed.append(sdkconfig_path)

    if changed:
        for path in changed:
            print(f"Updated {path.relative_to(PROJECT_DIR)}")
    else:
        print("No changes needed.")

    print(f"Selected board: {args.board}")
    print("Next step: run `idf.py reconfigure build` (or `idf.py flash monitor`).")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except RuntimeError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        raise SystemExit(1)
